# Change these first
owner: Ein-Tim
repo: uptime-monitoring

sites:
  - name: Corona-Warn-App website
    url: https://www.coronawarn.app
# this does not work, thus commented out
#  - name: CWA Logupload
#    url: https://logupload.coronawarn.app
  - name: CWA Main Server
    url: https://svc90.main.px.t-online.de/
  - name: CWA RAT portal
    url: https://schnelltestportal.de
  - name: CWA RAT map
    url: https://map.schnelltestportal.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-monitoring
  logoUrl: https://avatars.githubusercontent.com/u/67682506?v=4
  name: Status page
  introTitle: "Ein-Tim's status page"
  introMessage: I use this status page to monitor websites & endpoints I'm interested in!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
commitMessages:
  commitAuthorName: "Ein-Tim"
  commitAuthorEmail: "67682506+Ein-Tim@users.noreply.github.com"
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime] [BOT]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime] [BOT]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime] [BOT]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime] [BOT]"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
